config/routes.rb
Rails.application.routes.draw do
  resources :bars, only: [:index]
  resources :categories
  resources :dramas, only: [:index]
  resources :articles, only: [:index, :show]
  devise_for :users
  get 'kakaos/show'
  resources :comics, only: [:index, :show]
  get "search" => "articles#search"
  resources :daums, only: [:show]
  resources :kakaos, only: [:show]
  get 'home/index'
  root "comics#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_one_attached :image

    def self.search(search)
        return Article.all unless search
        Article.where(['title LIKE ?', "%#{search}%"])
      end
end

app/models/bar.rb
class Bar < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :dramas, dependent: :destroy
end

app/models/comic.rb
class Comic < ApplicationRecord
    has_one_attached :image

end

app/models/daum.rb
class Daum < ApplicationRecord
    has_one_attached :image
end

app/models/drama.rb
class Drama < ApplicationRecord
    has_one_attached :image
    belongs_to :category
end

app/models/kakao.rb
class Kakao < ApplicationRecord
    has_one_attached :image
end

app/models/pie.rb
class Pie < ApplicationRecord
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/dramas_controller.rb
class DramasController < ApplicationController
    def index
        
    if params.has_key?(:category)
        @category=Category.find_by(name: params[:category])
        @dramas = Drama.where(category: @category)
      else
      @dramas = Drama.all
      end
  
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kakaos_helper.rb
module KakaosHelper
end

app/helpers/pies_helper.rb
module PiesHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/dramas/index.html.erb
  
<div class="container mt-4">
  <section class="hero is-small has-background-info-light">
    <div class="hero-body">
      <div class="container  has-text-centered">
        <h1 class="title is-size-3">
          <i class="fas fa-tv mr-3"></i>Dramas&Movies based on Webtoon
        </h1>
      </div>
    </div>
  </section>
  <div class="columns">
    <div class="column is-one-fifth">
      <aside class="menu mt-6">
        <p class="menu-label is-size-4 title">
          List
        </p>
        <ul class="menu-list pt-4">
          <%Category.all.each do |cat|%>
            <li><%=link_to cat.name, dramas_path(category: cat.name)%></li>
            <hr>
          <% end %>
        </ul>
      </aside>
    </div>
    <div class="column mt-6 ml-4">
      <% @dramas.each do |drama| %>
        <article class="media">
          <div class="media-left">
            <figure>
              <%= image_tag drama.image %>
            </figure>
          </div>
          <div class="media-content ml-4">
            <div class="is-size-4 has-background-link-light has-text-centered has-text-weight-bold">
              <%= drama.title %>
            </div>
            <br>
            <div class="content">
              <p class="has-text-grey">
                Characters<br>
              </p>
              <%= drama.character %><br>
              <br>
              <p class="has-text-grey">
                Brief Story<br>
                <br>
              </p>
              <%= drama.desc %>
            </div>
          </div>
        </article>
      <% end %>
    </div>
  </div>
</div>
    