config/routes.rb
Rails.application.routes.draw do
  resources :bars, only: [:index]
  resources :categories
  resources :dramas, only: [:index]
  resources :articles, only: [:index, :show]
  devise_for :users
  get 'kakaos/show'
  resources :comics, only: [:index, :show]
  get "search" => "articles#search"
  resources :daums, only: [:show]
  resources :kakaos, only: [:show]
  get 'home/index'
  root "comics#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_one_attached :image

    def self.search(search)
        return Article.all unless search
        Article.where(['title LIKE ?', "%#{search}%"])
      end
end

app/models/bar.rb
class Bar < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :dramas, dependent: :destroy
end

app/models/comic.rb
class Comic < ApplicationRecord
    has_one_attached :image

end

app/models/daum.rb
class Daum < ApplicationRecord
    has_one_attached :image
end

app/models/drama.rb
class Drama < ApplicationRecord
    has_one_attached :image
    belongs_to :category
end

app/models/kakao.rb
class Kakao < ApplicationRecord
    has_one_attached :image
end

app/models/pie.rb
class Pie < ApplicationRecord
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!
    
    def index 
        @articles=Article.all
    end
    def show
        @article=Article.find(params[:id])
    end
    def search
        @articles = Article.search(params[:search])
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kakaos_helper.rb
module KakaosHelper
end

app/helpers/pies_helper.rb
module PiesHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/articles/index.html.erb
<div class="container mt-4 ">
  <section class="hero is-small has-background-info-light">
    <div class="hero-body">
      <div class="container  has-text-centered">
        <h1 class="title is-size-3">
          <i class="fas fa-paper-plane mr-3"></i>Webtoon News in Korea
        </h1>
        <%= form_tag(search_path,:method => 'get') do %>
          <%= text_field_tag :search%>
          <%= submit_tag 'Search', class:"button is-warning is-inverted", :name => nil %>
        <% end %>
      </div>
    </div>
  </section>
  <div class="columns is-multiline is-mobile">
    <%@articles.each do |article|%>
      <div class="column mt-4 is-half">
        <div class="box">
          <article class="media">
            <div class="media-left">
              <%if article.image.attached?%>
                <figure class="image is-128x128">
                  <div><%=link_to (image_tag article.image),article_path(article)%></div>
                </figure>
              <% end %>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong><%=article.title%></strong>
                  <br>
                  <%=truncate(article.desc, length: 96, separator: ' ')%>
                </p>
              </div>
              <nav class="level is-mobile">
                <div class="level-left">
                  <p class="level-item" aria-label="reply">
                    <%=article.created_at.strftime("%Y-%m-%d")%> | <%=article.reporter%>
                  </p>
                </div>
              </nav>
            </div>
          </article>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/search.erb
<div class="container mt-4">
  <section class="hero is-small has-background-primary-light">
    <div class="hero-body">
      <div class="container  has-text-centered">
        <h1 class="title is-size-3">
          Search result
        </h1>
      </div>
    </div>
  </section>
  <div class="columns is-centered is-multiline">
    <%@articles.each do |article|%>
      <div class="column my-5 is-8">
        <div class="box">
          <article class="media">
            <div class="media-left">
              <%if article.image.attached?%>
                <figure class="image is-128x128">
                  <div><%=link_to (image_tag article.image),article_path(article)%></div>
                </figure>
              <% end %>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong><%=article.title%></strong>
                  <br>
                  <%=truncate(article.desc, length: 96, separator: ' ')%>
                </p>
              </div>
              <nav class="level is-mobile">
                <div class="level-left">
                  <p class="level-item" aria-label="reply">
                    <%=article.created_at.strftime("%Y-%m-%d")%> | <%=article.reporter%>
                  </p>
                </div>
              </nav>
            </div>
          </article>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container ">
  <div class="columns is-centered">
    <div class="column is-10">
      <p class="title is-2 mt-4"><%=@article.title%></p>
      <p class="subtitle mt-2"><%=@article.created_at.strftime("%Y-%m-%d")%> | <%=@article.reporter%></p>
      <div class="card ">
        <div class="card-image has-text-centered">
          <figure>
            <div><%=image_tag @article.image%></div>
          </figure>
        </div>
        <div class="card-content">
          <div class="content ">
            <p class="is-size-4"><%=@article.desc%></p>
            <br>
            <%=@article.created_at.strftime("%Y-%m-%d")%> | <%=@article.reporter%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>