config/routes.rb
Rails.application.routes.draw do
  resources :bars, only: [:index]
  resources :categories
  resources :dramas, only: [:index]
  resources :articles, only: [:index, :show]
  devise_for :users
  get 'kakaos/show'
  resources :comics, only: [:index, :show]
  get "search" => "articles#search"
  resources :daums, only: [:show]
  resources :kakaos, only: [:show]
  get 'home/index'
  root "comics#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_one_attached :image

    def self.search(search)
        return Article.all unless search
        Article.where(['title LIKE ?', "%#{search}%"])
      end
end

app/models/bar.rb
class Bar < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :dramas, dependent: :destroy
end

app/models/comic.rb
class Comic < ApplicationRecord
    has_one_attached :image

end

app/models/daum.rb
class Daum < ApplicationRecord
    has_one_attached :image
end

app/models/drama.rb
class Drama < ApplicationRecord
    has_one_attached :image
    belongs_to :category
end

app/models/kakao.rb
class Kakao < ApplicationRecord
    has_one_attached :image
end

app/models/pie.rb
class Pie < ApplicationRecord
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    @comics=Comic.all
    @daums=Daum.all
    @kakaos=Kakao.all
    @platforms=Platform.all
  end

  def show
    @comic=Comic.find(params[:id])

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kakaos_helper.rb
module KakaosHelper
end

app/helpers/pies_helper.rb
module PiesHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/comics/index.html.erb
<div class="container mt-4">
  <section class="hero is-small has-background-info-light">
    <div class="hero-body">
      <div class="container  has-text-centered">
        <h1 class="title is-size-3">
          <i class="fas fa-sort-amount-up-alt mr-3"></i>Webtoon Rankings for Major Platforms
        </h1>
      </div>
    </div>
  </section>
  <div class="columns mt-4 is-multiline is-mobile">
    <div class="column is-4 mt-4 has-text-centered">
      <div class="tile notification has-background-success-light ">
        <img src="naver.png" class="image is-32x32 mr-3">
        <p class="has-text-weight-bold is-size-4 ">
          Naver
        </p>
      </div>
      <%@count = 0%>
      <%@comics.each do |comic|%>
        <div class="columns">
          <div class="column is-narrow has-text-centered">
            <div style="width: 40px;">
              <p class="title is-5">No. <span class="is-size-3"><%=@count+=1%></span></p>
            </div>
          </div>
          <div class="column ">
            <%if comic.image.attached?%>
              <div><%=link_to (image_tag comic.image),comic_path(comic) , class:"image ml-5 image is-3by2"%></div>
            <% end %>
            <div class="title mt-3"><%=comic.title%></div>
            <div class="subtitle has-text-grey"><%=comic.genre%> | <%=comic.author%></div>
          </div>
        </div>
      <%end%>
    </div>
    <div class="column box has-text-centered is-4 mt-4">
      <div class="tile notification has-background-danger ">
        <img src="daum.png" class="image is-32x32 mr-3">
        <p class="has-text-weight-bold is-size-4 ">
          Daum
        </p>
      </div>
      <%@count = 0%>
      <%@daums.each do |daum|%>
        <div class="columns">
          <div class="column is-narrow has-text-centered">
            <div style="width: 50px;">
              <p class="title is-5">No. <span class="is-size-3"><%=@count+=1%></span></p>
            </div>
          </div>
          <div class="column">
            <%if daum.image.attached?%>
              <div><%=link_to (image_tag daum.image),daum_path(daum) , class:"image ml-5 is-3by2"%></div>
            <% end %>
            <div class="title mt-3"><%=daum.title%></div>
            <div class="subtitle has-text-grey"><%=daum.genre%> | <%=daum.author%></div>
          </div>
        </div>
      <%end%>
    </div>
    <div class="column  is-4 mt-4">
      <div class="tile notification has-background-warning ">
        <img src="kakao.png" class="image is-32x32 mr-3">
        <p class="has-text-weight-bold is-size-4 ">
          Kakao page
        </p>
      </div>
      <%@count = 0%>
      <%@kakaos.each do |kakao|%>
        <div class="columns has-text-centered">
          <div class="column is-narrow has-text-centered">
            <div style="width: 50px;">
              <p class="title is-5">No. <span class="is-size-3"><%=@count+=1%></span></p>
            </div>
          </div>
          <div class="column">
            <%if kakao.image.attached?%>
              <div><%=link_to (image_tag kakao.image),kakao_path(kakao) , class:"image ml-5 is-3by2"%></div>
            <% end %>
            <div class="title mt-3"><%=kakao.title%></div>
            <div class="subtitle has-text-grey"><%=kakao.genre%> | <%=kakao.author%></div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/comics/show.html.erb
<div class= "container">
  <div class="columns mt-4">
    <div class= "column is-6">
      <%if @comic.image.attached?%>
        <%=image_tag @comic.image %>
      </div>
    <% else %>
      <%=image_tag ("https://via.placeholder.com/649x360?text=No+image") %>
    <% end %>
    <div class= "column is-6">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title has-background-white-ter is-size-3 ">
            <%=@comic.title%>
          </p>
        </header>
        <header class="card-header">
          <p class="card-header-subtitle is-size-5 is-italic ml-3">
            Author: <%=@comic.author%> / Genre: <%=@comic.genre%>
          </p>
        </header>
        <div class="card-content ml-3">
          <h5><%=@comic.desc%></h5>
        </div>
        <footer class="card-footer">
          <a href="#" class="card-footer-item "><i class="fas fa-external-link-square-alt mr-2"></i>
            Try the first episode
          </a>
        </footer>
      </div>
    </div>
  </div>
</div>